[modules]
autoload = yes

; Critical WebRTC modules
load = res_pjsip_transport_websocket.so
load = res_srtp.so

; Explicitly NOLOAD
noload = app_voicemail.so
noload = chan_dahdi.so
noload = codec_dahdi.so
noload = chan_oss.so
noload = chan_alsa.so
noload = chan_skinny.so
noload = chan_mgcp.so
noload = chan_sip.so
